# Site settings
title: Sophie de Brabander
email: hi@sophiedebrabander.be
description: ""
baseurl: ""
url: "http://sophiedebrabander.be"
username: "zofie"

# Build settings
markdown: kramdown
permalink: pretty
