url: https://zofie.github.io
baseurl:

# Site settings
title: Zofie
email: hallo@zofie.be
description: Freelance Front-end Developer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/zofie
  - title: facebook
    url: https://www.facebook.com/sophiedebrabander
  - title: instagram
    url: http://instagram.org/zofie
  - title: bitbucket
    url: http://bitbucket.org/Zofie
  - title: github
    url: http://github.com/Zofie

# Postal address (add as many lines as necessary)
address:
  - line: Ghent
  - line: Belgium

# Build settings
markdown: kramdown
permalink: pretty
