title: 'Sophie de Brabander'
author: 'Sophie de Brabander'
description: 'Front-end developer'
exclude: ['_site','scss', '*scss','Gem*','Guard*','*rb','.sass-cache','.git*','config.rb','*.md','*.json','docroot','node_modules','gulpfile.js']
